### PR TITLE
Add addr in broekr log

### PR DESCRIPTION
**Pull request by Shoothzj**

### CODE REVIEW

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by muXxer** [comment]
@Shoothzj you are causing a nil pointer exception with your added log.

```
hornet    | 2022/04/08 17:42:41 http: panic serving 127.0.0.1:56254: runtime error: invalid memory address or nil pointer dereference
hornet    | goroutine 887 [running]:
hornet    | net/http.(*conn).serve.func1()
hornet    |     /usr/local/go/src/net/http/server.go:1825 +0xbf
hornet    | panic({0x1d5f640, 0x3762500})
hornet    |     /usr/local/go/src/runtime/panic.go:844 +0x258
hornet    | net/url.(*URL).String(0x0)
hornet    |     /usr/local/go/src/net/url/url.go:800 +0x40
hornet    | github.com/fhmq/hmq/broker.(*Broker).handleConnection(0xc0001942d0, 0x0, {0x28a69a0?, 0xc002fb8a20})
hornet    |     /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20220404124133-a85e9904c2f4/broker/broker.go:286 +0x27d
hornet    | github.com/fhmq/hmq/broker.(*Broker).wsHandler(0x1f51540?, 0xc00281f800?)
hornet    |     /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20220404124133-a85e9904c2f4/broker/broker.go:174 +0x29
hornet    | golang.org/x/net/websocket.Server.serveWebSocket({{0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, 0x0}, ...}, ...)
hornet    |     /go/pkg/mod/golang.org/x/net@v0.0.0-20220403103023-749bd193bc2b/websocket/server.go:89 +0x15d
hornet    | golang.org/x/net/websocket.Server.ServeHTTP(...)
hornet    |     /go/pkg/mod/golang.org/x/net@v0.0.0-20220403103023-749bd193bc2b/websocket/server.go:70
hornet    | net/http.(*ServeMux).ServeHTTP(0x0?, {0x2899b78, 0xc0000beee0}, 0xc002159900)
hornet    |     /usr/local/go/src/net/http/server.go:2462 +0x149
hornet    | net/http.serverHandler.ServeHTTP({0xc00305c450?}, {0x2899b78, 0xc0000beee0}, 0xc002159900)
hornet    |     /usr/local/go/src/net/http/server.go:2916 +0x43b
hornet    | net/http.(*conn).serve(0xc002f9b540, {0x289b2b0, 0xc00313dc50})
hornet    |     /usr/local/go/src/net/http/server.go:1966 +0x5d7
hornet    | created by net/http.(*Server).Serve
hornet    |     /usr/local/go/src/net/http/server.go:3071 +0x4db
hornet    | 2022/04/08 17:42:41 http: panic serving 127.0.0.1:56258: runtime error: invalid memory address or nil pointer dereference
```

**Comment by Shoothzj** [comment]
@muXxer I am sorry. How to reproduce it? connected using websocket?
It's midnight in my timezone. I think I can create pr to fix it tomorrow.

**Pull request merged**
