### PR TITLE
Allow check if clientId connects

### PR DESCRIPTION
**Pull request by Shoothzj**

### CODE REVIEW

**Comment by Shoothzj** [comment]
@chowyu08 PTAL

**Comment by chowyu08** [comment]
设备状态支持系统topic，这个函数只支持单机模式调用

**Comment by Shoothzj** [comment]
@chowyu08 Could you please explain more ?

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by chowyu12** [comment]
https://github.com/fhmq/hmq#onlineoffline-notification

**Comment by Shoothzj** [comment]
> https://github.com/fhmq/hmq#onlineoffline-notification

thanks for your reply

**Pull request closed without merging**
